package com.management.studentmanagement.common;

public class ResponseMessage {
	
	public static final String SUCCESSFUL = "SUCCESSFUL";
	public static final String STUDENT_NOT_FOUND= "STUDENT_NOT_FOUND";
	public static final String USER_NOT_FOUND= "USER_NOT_FOUND";
	public static final String COURSE_NOT_FOUND= "COURSE_NOT_FOUND";
	public static final String THE_STUDENT_ALREADY_HAS_THE_COURSE= "THE_STUDENT_ALREADY_HAS_THE_COURSE";
	public static final String THE_STUDENT_DOESNT_HAVE_THE_COURSE= "THE_STUDENT_DOESNT_HAVE_THE_COURSE";
	public static final String THE_COURSE_ALREADY_EXISTS = "THE_COURSE_ALREADY_EXISTS";
	public static final String THERE_ARE_STUDENTS_ENROLLED_IN_THE_COURSE_IT_CANNOT_BE_DELETED = "THERE_ARE_STUDENTS_ENROLLED_IN_THE_COURSE_IT_CANNOT_BE_DELETED";
	public static final String MAXIMUM_COURSES_THAT_CAN_BE_TAKEN = "MAXIMUM_COURSES_THAT_CAN_BE_TAKEN";
	public static final String MAXIMUM_NUMBER_OF_STUDENTS_POSSIBLE ="MAXIMUM_NUMBER_OF_STUDENTS_POSSIBLE";
	public static final String THE_STUDENT_DOES_NOT_HAVE_ANY_COURSES ="THE_STUDENT_DOES_NOT_HAVE_ANY_COURSES";
	public static final String THE_COURSE_DOES_NOT_HAVE_ANY_STUDENT ="THE_COURSE_DOES_NOT_HAVE_ANY_STUDENT";
	public static final String THE_STUDENT_HAS_A_COURSE_CANT_BE_DELETED ="THE_STUDENT_HAS_A_COURSE_CANT_BE_DELETED";
	public static final String FIRST_REMOVE_COURSES ="FIRST_REMOVE_COURSES";
	
}
